### ISSUE TITLE
`rust-toolchain.toml` is no longer recognized

### ISSUE THREAD

**Issue by stinodego** [PyO3/maturin-action#215]
A recent update seems to have broken this functionality.

This is a recent run (installs stable, ignoring `rust-toolchain.toml`):
https://github.com/stinodego/polars/actions/runs/6384664783/job/17327784276

This is a slightly older run of ~6 hours ago (installs nightly as specified in `rust-toolchain.toml`):
https://github.com/stinodego/polars/actions/runs/6380623219/job/17315365326

~Maybe it's because of the `working-directory` specification?~ Same issue when not using `working-directory`.

**Comment by messense** [comment]
So #213 could have break this.

https://github.com/PyO3/maturin-action/blob/33928228f0d5da9e8e3d48ac01135041da64e7a1/src/index.ts#L203-L204

We should walk the directories up to `$GITHUB_WORKSPACE` to find a `rust-toolchain.toml` instead of just check it once. I don't have time to fix it today, so pull requests are welcome.

**Comment by messense** [comment]
Fixed in #217 and published in `v1`.

**Comment by stinodego** [comment]
Can confirm that this was fixed, thanks!
